spring:
  h2:
    console:
      enabled: true
      path: /h2 # ~/h2? console ??
      settings:
        web-allow-others: true # ?? ip? ??
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
